apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
spec:
  containers:
  - name: backend
    image: shantibb/backend
    envFrom:
    - configMapRef:
        name: backend-config
    ports:
    - containerPort: 8000
