apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:latest
    envFrom:
    - configMapRef:
        name: postgres-config
    ports:
    - containerPort: 5432 
